version: "3"

services:

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "127.0.0.1:63790:6379"

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - "datavolume:/var/lib/mysql"
    env_file:
     - .env
    expose:
      - "3306"
    ports:
      - "33060:3306"

  berater:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: bash -c "/wait-for-it.sh mysql:3306 -- flask run --host=0.0.0.0 --port=80"
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
    links:
      - mysql
    depends_on:
      - mysql
      - redis

volumes:
  datavolume: 
