version: "3"

services:

  redis:
    image: redis
    container_name: berater_redis
    expose:
      - 6379
    ports:
      - "127.0.0.1:63790:6379"

  mysql:
    restart: always
    image: mysql:5.7
    container_name: berater_mysql
    volumes:
      - "datavolume:/var/lib/mysql"
    env_file:
     - .env
    expose:
      - "3306"
    ports:
      - "33060:3306"

  berater:
    container_name: berater_main
    build: .
    command: bash -c "/wait-for-it.sh mysql:3306 -- supervisord"
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
    links:
      - mysql
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx
    container_name: berater_nginx
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    links:
      - berater

volumes:
  datavolume: 
