version: "3"

services:

  redis:
    image: redis
    container_name: berater_redis
    volumes:
      - "redis-data:/data"
    expose:
      - 6379
    ports:
      - "127.0.0.1:63790:6379"

  mysql:
    restart: always
    image: mysql:5.7
    container_name: berater_mysql
    volumes:
      - "datavolume:/var/lib/mysql"
    env_file:
      - .env
    expose:
      - "3306"
    ports:
      - "127.0.0.1:33060:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake

  berater:
    container_name: berater_main
    build: .
    command: bash -c "/wait-for-it.sh mysql:3306 -- supervisord"
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./conf/berater-supervisord.conf:/etc/supervisor/supervisord.conf"
      - "/var/log/berater:/log"
    links:
      - mysql
    depends_on:
      - mysql
      - redis

  celery:
    container_name: berater_celery
    build: .
    command: bash -c "/wait-for-it.sh redis:6379 -- supervisord"
    env_file:
      - .env
    ports:
      - "127.0.0.1:5555:5555"
    volumes:
      - "./conf/celery-supervisord.conf:/etc/supervisor/supervisord.conf"
      - "/var/log/celery:/log"
    depends_on:
      - redis

  wx-auth:
    container_name: berater_wx_auth
    #    image: registry.cn-shenzhen.aliyuncs.com/inhzus/wx-auth:latest
    image: auth:latest
    ports:
      - "127.0.0.1:8001:80"
      - "127.0.0.1:8002:443"

volumes:
  datavolume:
  redis-data:
